# -*- coding: utf-8 -*-
"""AtividadeSistemaFila_ModelagemSimulação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fqw0hlQcv8_K8ewWx8XDiU_CnpcdiGcu
"""

# • Nome do serviço (ex: "RU da Faculdade")
# • Horário de observação (30 minutos - ex: "12h às 12h30")
# • Número de servidores (quantos atendentes/caixas/computadores)
# • 30 dados de chegadas (pessoas que chegam por minuto)
# • 30 tempos de atendimento (tempo em minutos para cada atendimento)

"""
==========================================
 PROGRAMA DE ANÁLISE DE FILAS (30 MINUTOS)
==========================================

Como usar:
1. Execute o programa.
2. Escolha o tipo de serviço que quer analisar (ex: RU, supermercado etc).
3. Informe:
   - Nome do serviço
   - Horário de observação (ex: 12h às 12h30)
   - Quantos servidores (atendentes/caixas)
4. Escolha se quer:
   - (1) Gerar dados aleatórios para simular
   - (2) Inserir os 30 valores manualmente

O programa calcula automaticamente:
- λ (lambda): taxa média de chegada por minuto
- μ (mi): taxa média de atendimento
- ρ (rô): nível de ocupação do sistema

Interpretação automática:
- ρ < 0.5 → Sistema subutilizado
- 0.5 ≤ ρ < 0.8 → Sistema eficiente
- 0.8 ≤ ρ < 1.0 → Sistema no limite
- ρ ≥ 1.0 → Sistema em colapso

Ao final, o programa mostra:
- Dados coletados (chegadas e atendimentos)
- Resultados dos cálculos
- Interpretação e recomendação

Para rodar novamente, basta responder "s" quando perguntado.


Codigo está construido por métodos para facilitar a implementação.
"""

import numpy as np

class SistemaFila:
        def __init__(fila, nome_servico, horario, servidores, chegadas, tempos_atendimento):
                fila.nome_servico = nome_servico
                fila.horario = horario
                fila.servidores = servidores
                fila.chegadas = np.array(chegadas)
                fila.tempos_atendimento = np.array(tempos_atendimento)
                fila.resultados = {}

        def criar_sistema_fila():
                print("\n\n=== CRIAÇÃO DE NOVO SISTEMA DE FILA ===")
                nome_servico = input("Nome do serviço: ")
                horario = input("Horário de observação (ex: 12h às 12h30): ")
                servidores = int(input("Número de servidores: "))

                print("\nEscolha como inserir os dados:")
                print("1 - Gerar dados aleatórios (simulação aproximada)")
                print("2 - Inserir manualmente (observação)")
                opcao = input("Opção (1/2): ")

                if opcao == "1":
                    media_chegada = float(input("\nMédia esperada de chegadas por minuto: "))
                    media_atendimento = float(input("Tempo médio de atendimento (minutos): "))

                    # Gerando automaticamente 30 valores
                    chegadas = np.random.poisson(media_chegada, 30) # (media de chegada, tempo médio)
                    tempos_atendimento = np.random.normal(media_atendimento, 0.3, 30) # (media atendimento, variacao da media, tempo médio)

                    print("\n✅ Dados simulados com sucesso!\n")

                elif opcao == "2":
                    chegadas = []
                    print("\nDigite o número de chegadas por minuto (30 valores):")
                    for i in range(30):
                        valor = int(input(f"  Minuto {i+1}: "))
                        chegadas.append(valor)

                    tempos_atendimento = []
                    print("\nDigite o tempo de atendimento de cada cliente (30 valores):")
                    for i in range(30):
                        valor = float(input(f"  Atendimento {i+1}: "))
                        tempos_atendimento.append(valor)

                    chegadas = np.array(chegadas)
                    tempos_atendimento = np.array(tempos_atendimento)

                else:
                    print("Opção inválida! Encerrando.")
                    return None


                # Cria o objeto com os dados coletados e já retorna com o objeto iniciado
                sistema = SistemaFila(nome_servico, horario, servidores, chegadas, tempos_atendimento)
                return sistema

        def calcular(fila):
                # λ = total de chegadas / tempo de observação (30 min)
                lambd = np.sum(fila.chegadas) / 30.0

                # μ = 1 / tempo médio de atendimento
                mu = 1 / np.mean(fila.tempos_atendimento)

                # ρ = λ / (servidores * μ)
                rho = lambd / (fila.servidores * mu)

                fila.resultados = {
                    "lambda": lambd, # λ
                    "mu": mu, # μ
                    "rho": rho, # ρ
                    "media_atendimento": np.mean(fila.tempos_atendimento),
                    "total_chegadas": np.sum(fila.chegadas)
                }

        def interpretacao(fila):
                rho = fila.resultados["rho"]
                if rho < 0.5:
                    return "Sistema SUBUTILIZADO."
                elif 0.5 <= rho < 0.8:
                    return "Sistema EFICIENTE."
                elif 0.8 <= rho < 1.0:
                    return "Sistema NO LIMITE.\nRecomendação: CRITICA! Adicione mais servidores"
                else:
                    return "Sistema EM COLAPSO - fila cresce indefinidamente!\nRecomendação: URGENTE! Adicione vários servidores"

        def exibir_resultados(fila):
                print(f"\n\nANÁLISE DE FILAS - {fila.nome_servico}")
                print(f"Horário: {fila.horario}")
                print("=" * 40)
                print("DADOS COLETADOS:")
                print(f"• Total de chegadas em 30 min: {fila.resultados['total_chegadas']} pessoas")
                print(f"• Número de servidores: {fila.servidores}")
                print(f"• Tempo médio de atendimento: {fila.resultados['media_atendimento']:.2f} min")
                print("\nCÁLCULOS:")
                print(f"• λ (taxa de chegada): {fila.resultados['lambda']:.2f} pessoas/minuto")
                print(f"• μ (taxa de atendimento): {fila.resultados['mu']:.2f} atendimentos/minuto")
                print(f"• ρ (ocupação): {fila.resultados['rho']:.2f}")
                print("\nInterpretacao:")
                print(f"• {fila.interpretacao()}")


def main():
        fila = SistemaFila.criar_sistema_fila()
        SistemaFila.calcular(fila)
        SistemaFila.exibir_resultados(fila)

if __name__ == '__main__':
        while True:
                main()
                denovo = input('\nDeseja calcular novamente? (s/n): ').strip().lower()
                if denovo != 's':
                    print('Encerrado.')
                    break